// In-extension report page. Renders the timeline and the session-replay player
// directly into the page DOM via external scripts only (Manifest V3 page CSP is
// script-src 'self'); the rrweb-player UMD is loaded as a classic script from
// dist/rrweb-player.js (copied there by build.mjs). Exports the self-contained
// file on demand using the same renderer + mount the export embeds.

import { renderReport, mountReplay, mountAudio, REPORT_CSS, REPLAY_CSS } from "./renderer.js";
import { buildReportHTML } from "./report-builder.js";
import { renderErrorReport } from "./issue-link.js";

const ENV = { version: chrome.runtime.getManifest().version, userAgent: navigator.userAgent };
const params = new URLSearchParams(location.search);
const key = params.get("key");

// A stored report's rrwebEvents may be a JSON string (new — background.js stores
// it stringified so deep DOM survives chrome.storage.local's Mojo ~100-depth cap)
// or a plain array (old reports, or the degraded no-replay path). Normalize to an
// array once here so renderer.js and report-builder.js are unchanged downstream.
function asEventArray(v) {
  if (Array.isArray(v)) return v;
  if (typeof v !== "string") return [];
  try {
    return JSON.parse(v);
  } catch {
    return [];
  }
}

function fail(message) {
  const app = document.getElementById("app");
  app.style.padding = "30px";
  app.style.color = "#f85149";
  renderErrorReport(app, message, ENV);
}

async function load() {
  const style = document.createElement("style");
  style.textContent = REPORT_CSS + REPLAY_CSS;
  document.head.appendChild(style);

  if (!key) return fail("No report key provided.");
  const stored = await chrome.storage.local.get(key);
  const report = stored[key];
  if (!report) return fail("Report not found (it may have been cleared).");
  report.rrwebEvents = asEventArray(report.rrwebEvents);

  renderReport(document.getElementById("app"), report);

  // dist/rrweb-replay.js defines the RRWebReplayer global; absent if unbuilt.
  const ReplayerCtor = globalThis.RRWebReplayer;
  const hasReplay = !!(ReplayerCtor && report.rrwebEvents && report.rrwebEvents.length > 1);
  if (hasReplay) {
    const section = document.getElementById("replay-section");
    section.hidden = false; // unhide BEFORE mounting so the player measures real dimensions
    try {
      // mountReplay also drives the narration audio in sync (one player).
      mountReplay(document.getElementById("replay"), report, ReplayerCtor);
    } catch (err) {
      // A broken replay shouldn't take the timeline down with it.
      renderErrorReport(document.getElementById("replay"), "Replay failed to mount: " + err, ENV);
    }
  }

  // Standalone narration player ONLY when there's no replay to drive it.
  if (!hasReplay && report.audio && report.audio.dataUrl) {
    const audioSection = document.getElementById("audio-section");
    audioSection.hidden = false;
    try {
      mountAudio(document.getElementById("audio"), report);
    } catch (err) {
      renderErrorReport(document.getElementById("audio"), "Audio failed to mount: " + err, ENV);
    }
  }

  // Player UMD/CSS strings generated by build.mjs; absent if the build hasn't
  // run — the export then simply omits the replay player.
  let replayAssets = null;
  try {
    replayAssets = await import("./src/generated/player-assets.js");
  } catch {
    console.warn("player-assets.js missing — run `npm run build`; exporting without replay player");
  }

  document.getElementById("download").addEventListener("click", () => {
    const html = buildReportHTML(report, replayAssets);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const stamp = new Date(report.meta.capturedAt).toISOString().replace(/[:.]/g, "-");
    const a = document.createElement("a");
    a.href = url;
    a.download = "openjam-" + stamp + ".html";
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  });
}

load();
